langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: trusty
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: 862ee965-0198-4b24-8ea6-135784cd4ae9
  app: brownfield-ca-sm
  run: rails db:migrate
